# Generated by Django 2.2.9 on 2021-12-21 08:10

from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20211221_1106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('author'), nulls_last=True)]},
        ),
    ]
