# Generated by Django 2.2.16 on 2022-02-04 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_auto_20220203_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='author',
            new_name='author1',
        ),
    ]
