# Generated by Django 2.2.16 on 2022-02-04 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_auto_20220204_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='author1',
            new_name='author',
        ),
    ]
